name: waste_detector
description: Aplikasi deteksi sampah organik dan anorganik menggunakan AI

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # AI & Machine Learning
  tflite_flutter: ^0.11.0
  
  # Camera & Image
  camera: ^0.11.1
  image_picker: ^1.0.4
  image: ^4.1.3
  
  # UI Components
  cupertino_icons: ^1.0.2
  google_generative_ai: ^0.4.7

  # Permissions
  permission_handler: ^12.0.0+1
  
  # Storage
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/models/
    - assets/images/
    - assets/onboarding/